- name: Enable universe
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename}} universe
    - deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename}}-security universe
    - deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename}}-updates universe

- name: Install debconf-utils
  apt:
    name: debconf-utils
    state: present

- name: Configure package selections for MySQL
  debconf:
    name: mysql-apt-config
    question: "{{item.question}}"
    value: "{{item.value}}"
    vtype: "{{item.vtype}}"
  with_items:
    - { question: "mysql-apt-config/select-server", value: "mysql-8.0", vtype: "string" }
    - { question: "mysql-apt-config/select-product", value: "Ok", vtype: "select" }

- name: Add Oracle MySQL repository
  apt:
    deb: https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
    state: present

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Copy MySQL configuration file
  copy:
    src: files/mysql/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644

- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Install PHP
  apt:
    name:
      - php
      - php-curl
      - php-intl
      - libapache2-mod-php
    state: present

- name: Install Composer
  apt:
    name: composer
    state: present

- name: Generate a new DH group
  command: openssl dhparam -out /etc/ssl/private/dhparams_4096.pem 4096
  args:
    creates: /etc/ssl/private/dhparams_4096.pem

- name: Add certbot PPA repository
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  apt:
    name: certbot
    state: present

- name: Install SSL/TLS certificates
  command: certbot certonly --standalone -n --agree-tos -m {{myusername}}@{{mydomain}} --rsa-key-size 4096 -d {{mydomain}},www.{{mydomain}},mail.{{mydomain}}
  args:
    creates: /etc/letsencrypt/live/{{mydomain}}/

- name: Copy certificate renewal job
  copy:
    src: files/cron/renew-certificates
    dest: /etc/cron.weekly/renew-certificates
    owner: root
    group: root
    mode: 0755

- name: Enable Apache modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - headers
    - rewrite
    - ssl

- name: Copy Apache site configuration template
  template:
    src: "templates/apache2/mydomain.conf.j2"
    dest: "/etc/apache2/sites-available/{{mydomain}}.conf"
    owner: root
    group: root
    mode: 0644

- name: Copy Apache ssl configuration file
  copy:
    src: "files/apache2/ssl.conf"
    dest: "/etc/apache2/mods-available/ssl.conf"
    owner: root
    group: root
    mode: 0644

- name: Create web directory
  file:
    path: /var/www/{{mydomain}}/www/public
    state: directory

- name: Set web directory ownership and permissions
  file:
    path: "{{item}}"
    owner: www-data
    group: www-data
    mode: u=rwX,g=rwX,o=rX
    state: directory
  with_items:
    - /var/www/{{mydomain}}
    - /var/www/{{mydomain}}/www
    - /var/www/{{mydomain}}/www/public

- name: Set web directory group sticky bit
  file:
    path: /var/www/{{mydomain}}
    mode: g+s
    state: directory

- name: Disable Apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default
    state: absent

- name: Enable Apache site
  file:
    src: /etc/apache2/sites-available/{{mydomain}}.conf
    dest: /etc/apache2/sites-enabled/{{mydomain}}.conf
    state: link

- name: Restart installed services
  systemd:
    name: "{{item}}"
    enabled: yes
    state: restarted
  with_items:
    - apache2
    - mysql

- name: Update firewall rules
  ufw:
    name: "{{item}}"
    rule: allow
    state: enabled
  with_items:
    - Apache Full
    - OpenSSH
