---
- name: Orchestrate mailserver setup
  hosts: mailservers
  become: True
  tasks:
    - name: Enable universe
      apt_repository:
        repo: "{{item}}"
      with_items:
        - deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename}} universe
        - deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename}}-security universe
        - deb http://archive.ubuntu.com/ubuntu {{ansible_lsb.codename}}-updates universe

    - name: Create virtual mail user
      user:
        name: vmail
        comment: "virtual mail user"
        home: /var/spool/vmail
        shell: /usr/sbin/nologin
        system: yes

    - name: Install SQLite
      apt:
        name: sqlite3

    - name: Install Postfix
      apt:
        name:
         - postfix
         - postfix-sqlite

    - name: Install Dovecot
      apt:
        name:
         - dovecot-pop3d
         - dovecot-sqlite
         - dovecot-lmtpd

    - name: Install SpamAssassin
      apt:
        name:
          - spamassassin

    - name: Install OpenDKIM
      apt:
        name:
          - opendkim
          - opendkim-tools

    - name: Configure Postfix
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - {
            src: "files/etc/postfix/main.cf",
            dest: "/etc/postfix/main.cf",
          }
        - {
            src: "files/etc/postfix/master.cf",
            dest: "/etc/postfix/master.cf",
          }
        - {
            src: "files/etc/postfix/sqlite-virtual-mailbox-domains.cf",
            dest: "/etc/postfix/sqlite-virtual-mailbox-domains.cf",
          }
        - {
            src: "files/etc/postfix/sqlite-virtual-mailbox-maps.cf",
            dest: "/etc/postfix/sqlite-virtual-mailbox-maps.cf",
          }
        - {
            src: "files/etc/postfix/sqlite-virtual-alias-maps.cf",
            dest: "/etc/postfix/sqlite-virtual-alias-maps.cf",
          }

    - name: Configure Dovecot
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - {
            src: "files/etc/dovecot/conf.d/10-mail.conf",
            dest: "/etc/dovecot/conf.d/10-mail.conf"
          }
        - {
            src: "files/etc/dovecot/conf.d/10-auth.conf",
            dest: "/etc/dovecot/conf.d/10-auth.conf"
          }
        - {
            src: "files/etc/dovecot/conf.d/10-ssl.conf",
            dest: "/etc/dovecot/conf.d/10-ssl.conf"
          }
        - {
            src: "files/etc/dovecot/conf.d/10-master.conf",
            dest: "/etc/dovecot/conf.d/10-master.conf"
          }
        - {
            src: "files/etc/dovecot/dovecot-sql.conf.ext",
            dest: "/etc/dovecot/dovecot-sql.conf.ext"
          }
        - {
            src: "files/etc/dovecot/conf.d/auth-sql.conf.ext",
            dest: "/etc/dovecot/conf.d/auth-sql.conf.ext"
          }

    - name: Configure SpamAssassin
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - {
            src: "files/etc/mail/spamassassin/local.cf",
            dest: "/etc/mail/spamassassin/local.cf",
          }
        - {
            src: "files/etc/default/spamassassin",
            dest: "/etc/default/spamassassin",
          }

#    - name: Update SpamAssassin database
#      command: sa-update
#
    - name: Create OpenDKIM directories
      file:
        path: /etc/opendkim/keys/{{mydomain}}
        state: directory

    - name: Configure OpenDKIM
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - {
            src: "files/etc/opendkim.conf",
            dest: "/etc/opendkim.conf"
          }
        - {
            src: "files/etc/default/opendkim",
            dest: "/etc/default/opendkim"
          }
        - {
            src: "files/etc/opendkim/TrustedHosts",
            dest: "/etc/opendkim/TrustedHosts"
          }
        - {
            src: "files/etc/opendkim/KeyTable",
            dest: "/etc/opendkim/KeyTable"
          }
        - {
            src: "files/etc/opendkim/SigningTable",
            dest: "/etc/opendkim/SigningTable"
          }


    - name: Generate OpenDKIM Keys
      command: opendkim-genkey -s mail -d {{mydomain}}
      args:
        chdir: /etc/opendkim/keys/{{mydomain}}
        creates: /etc/opendkim/keys/{{mydomain}}/mail.private

    - name: Set OpenDKIM mail key ownership
      file:
        path: /etc/opendkim/keys/{{mydomain}}/mail.private
        owner: opendkim
        group: opendkim

    - name: Configure primary mail account and aliases (upload SQL)
      template:
        src: files/accounts.sqlite.sql
        dest: /tmp/accounts.sqlite.sql

    - name: Configure primary mail account and aliases (import SQL)
      shell: sqlite3 /etc/postfix/accounts.sqlite < /tmp/accounts.sqlite.sql
      args:
        executable: /bin/bash
        creates: /etc/postfix/accounts.sqlite

    - name: Configure primary mail account and aliases (delete SQL)
      file:
        path: /tmp/accounts.sqlite.sql
        state: absent

    - name: Restart installed services
      systemd:
        enabled: yes
        state: restarted
        name: "{{item}}"
      with_items:
        - spamassassin
        - opendkim
        - postfix
        - dovecot

    - name: Update firewall rules
      ufw:
        rule: allow
        name: "{{item}}"
      with_items:
        - Postfix
        - Dovecot Secure POP3
