---
- name: Orchestrate mailserver setup
  hosts: mailservers
  become: True
  tasks:
    - import_role:
        name: mailserver

    - name: Move DKIM key for Terraform
      local_action: command mv mail.dkim-value ../terraform/mail.dkim-value
      become: no
