---
- name: Orchestrate mailserver setup
  hosts: mailservers
  become: True
  tasks:
    - import_role:
        name: mailserver

    - name: Fetch public DKIM key for Terraform
      fetch:
        dest: ../terraform/mail.dkim-value
        src: /etc/opendkim/keys/{{domain}}/mail.dkim-value
        flat: yes
